{{- if .Values.user.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend-user
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.user.replicaCount }}
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
        version: {{ .Values.user.image.tag | quote }}
    spec:
      containers:
        - name: backend-user
          image: "{{ .Values.user.image.repository }}:{{ .Values.user.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: backend-secret
          env:
            {{- range $key, $value := .Values.user.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.user.resources | nindent 12 }}
{{- end }}
